version: '3.4'

services:
  tarefa-api:
    image: tarefa-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "PassTarefaDb"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
